title: Federico Magnani's blog
description: Rust, Computational Mathematics, Finance and other stuff. God bless pane & olio.
baseurl: "" # Leave empty for user sites, "/repo-name" for project sites
url: "https://fedemagnani.github.io" # Your GitHub Pages URL

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists


collections:
  projects:
    output: false
  writings:
    output: false


jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-HKMV72T3J1         
    anonymizeIp: true      

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-analytics


